# Hello! Hello! , there i have started learning Numpy .

In [1]:
import numpy as np

In [2]:
list = [1 , 2 , 3 , 4]
# Casting a list to array
arr = np.array(list)

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
# For 2-D arrays , we can cast a list of list
list = [[1 , 2 , 3] , [4 , 5 ,6] , [7 , 8 , 9]]
arr = np.array(list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# arange() will return an array in the range of [start , end) and we can also pass an additional step value , which tells
# the steps taken by currnt elemnt to get next element .
np.arange(0 , 10 , 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0 , 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# To generate array of zeroes
np.zeros(3)

array([0., 0., 0.])

In [13]:
# Creating a 2-D array using tuples
np.zeros((3 , 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# To create an array of 1's
np.ones(2)

array([1., 1.])

In [15]:
np.ones((2 , 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# linspace will give us 4 evenly distributed element in range of [0 , 7]
np.linspace(0 , 7 , 4)

array([0.        , 2.33333333, 4.66666667, 7.        ])

In [22]:
# Creating an identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [2]:
# Creating a matrix containing random elements .
np.random.rand(2)

array([0.46331041, 0.60816384])

In [3]:
np.random.rand(2 , 3)

array([[0.47442317, 0.73022176, 0.74840027],
       [0.55553281, 0.24339723, 0.7446407 ]])

In [4]:
# Rand don't take tuples as arguments .
np.random.rand((2 , 3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [5]:
# To get elements from gaussian distribution
np.random.randn(2)

array([ 0.4880171 , -1.34595329])

In [6]:
np.random.randn(4 , 4)

array([[-0.77327776,  1.37544432,  0.32489657,  0.18666655],
       [ 0.23479783, -1.25981232, -1.03999011, -0.67646092],
       [ 0.70832709,  0.04705362,  0.88769384,  1.56855276],
       [ 0.49977882, -0.59048545, -0.81072857,  1.46109694]])

In [7]:
# To get random integers from [start , end)
np.random.randint(1 , 100)

91

In [8]:
# To get random integers in matrix form , we have to pass 3rd argument
np.random.randint(1 , 100 , 10)

array([16, 38, 68, 96, 55,  1, 31, 14, 50, 53])

In [10]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
randArr = np.random.randint(1 , 100 , 10)
randArr

array([13, 63, 21, 21, 52, 97, 55, 72, 42, 40])

In [19]:
# to reshape an array , rememeber the arguments passed here must be such that , the new array's size is not changed
# Otherwise we may get an error .
arr.reshape(5 , 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
randArr

array([13, 63, 21, 21, 52, 97, 55, 72, 42, 40])

In [21]:
# To get max element
randArr.max()

97

In [22]:
# To ge min element
randArr.min()

13

In [23]:
# To get index value of the max element
randArr.argmax()

5

In [24]:
randArr.argmin()

0

In [26]:
arr.argmax()

9

In [28]:
# To get shape of array , we don't need to put parenthesis here .
arr.shape

(10,)

In [29]:
# To get what data types are present in array
arr.dtype

dtype('int32')

# Numpy Indexing And Selection

In [33]:
arr = np.arange(0 , 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# To get a value at any index .
arr[5]

5

In [37]:
arr = arr.reshape(11 , 1)
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [39]:
arr[5][0]

5

In [41]:
arr = arr.reshape(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# Slicing
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[:1]

array([0])

In [44]:
# last is exclusive and start is inclusive arr[start:last]
arr[0:5]

array([0, 1, 2, 3, 4])

In [46]:
# to change the value of any index
arr[0] = 15
arr

array([15,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[0:] = 100000
arr

array([100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000,
       100000, 100000, 100000])

In [50]:
arr = np.arange(0 , 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arrNew = arr[0:5]
arrNew[0:5] = 10
arrNew

array([10, 10, 10, 10, 10])

In [53]:
# We can see here , any change we have made in our new array , will be seen in the array from whom we created this new array
# The reason being we have just referenced the older elements to this new array(we have not copied the elements to new array)
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.arange(0 , 11)

In [55]:
# If we use copy() , to copy array elements to a new array , then any change made to the new array will not effect the 
# previous array .
arrNew = arr.copy()
arrNew

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [58]:
arrNew[0:7] = 1000
arrNew

array([1000, 1000, 1000, 1000, 1000, 1000, 1000,    7,    8,    9,   10])

In [59]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [61]:
# Creating a 2D array using nested lists
arr2D = np.array([[1 , 2 ,3] , [4 , 5 , 6] , [7 , 8 , 9]])
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
# Indexing n 2D arrays using double bracket
arr2D[0][2]

3

In [64]:
# Indexing in 2D arrays using single bracket , prefer this one .
arr2D[0 , 2]

3

In [68]:
# To get elements in chunk , here start is inclusive and is exclusive .
arr2D[0:2 ,1:3]

array([[2, 3],
       [5, 6]])

In [71]:
# This grabs all elements starting from row 0 and column 1 , till end .
arr2D[0: , 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [73]:
arr = np.arange(1 , 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
# We can compare the above array with any item having same datatype , which will return a boolean array .
boolArr = arr == 1
boolArr

array([ True, False, False, False, False, False, False, False, False,
       False])

In [79]:
# We can pass the above boolean array to the original array , and we will only get results on which this boolean array is true .
arr[boolArr]

array([1])

In [80]:
# More fashion way of getting the above desired elements , as we have got using arr[boolArr]
arr[arr == 1]

array([1])

# Numpy Operations

In [82]:
arr = np.arange(0 , 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Array with Array

In [83]:
# Adding two arrays
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [84]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [86]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [88]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [89]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [90]:
# On some mathematical operations , numpy gives warning instead of giving error .
# We know we can't divide a number by zero , so python gives error .
3/0

ZeroDivisionError: division by zero

In [91]:
# However numpy won't give an error , rather it will produce a warning , and the place where we will get num/0 division
# numpy will return "nan" instead .
arr/arr

C:\Users\asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [92]:
# On dividing arr with 1 , numpy will give "inf" , as output in the place of division of 1/0
1/arr

C:\Users\asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [93]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

# Universal array operations .

In [94]:
# to get square root of every element of the array .
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [95]:
np.log(arr)

C:\Users\asus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [96]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [97]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [98]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])